import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/ui/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto h-full w-full max-w-md bg-gray-100">
        <main className="h-screen bg-white">
          <Header />
          {children}
        </main>
        {/* 스크롤 이벤트 테스트 용 */}
        <div className="h-screen w-full bg-gray-200"></div>
      </body>
    </html>
  );
}
